name: wireless_term_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  flutter:
    sdk: flutter
  flutter_unity_widget: ^2022.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
